### ISSUE TITLE
i have an issue with compiling

### ISSUE THREAD

**Issue by babaisnyan** [Wunkolo/Maple2Tools#2]
do you mind releasing compiled stuffs?

**Comment by Wunkolo** [comment]
This is very vague.
What issue are you getting? Are you compiling on Linux? I do not have an officially supported windows build at the moment.

**Comment by ghost** [comment]
> do you mind releasing compiled stuffs?

I also ran into some roadblocks here is what helped me, the dependencies in the instructions only mentions
>cmake
>crypto++

but I also had to cd into the Maple2Tools/dependencies directory and clone 
https://github.com/mandreyel/mio into the 'mio' directory
https://github.com/catchorg/Clara into the 'Clara' directory
and then it worked like a charm


> This is very vague.
> What issue are you getting? Are you compiling on Linux? I do not have an officially supported windows build at the moment.

I think he is asking if you could put a compiled binary and/or zip in here 
https://github.com/Wunkolo/Maple2Tools/releases 
so everyone doesn't have to compile from source, I'd assume for Windows since MS2 runs on Windows

**Comment by Wunkolo** [comment]
> I also ran into some roadblocks here is what helped me

the command `git clone --recursive https://github.com/Wunkolo/Maple2Tools` does this all for you. I added it to the readme.

> I think he is asking if you could put a compiled binary and/or zip in here
> https://github.com/Wunkolo/Maple2Tools/releases
> so everyone doesn't have to compile from source, I'd assume for Windows since MS2 runs on Windows

I just made a make-shift windows build that seems to work.

Lemme know how it goes:

https://github.com/Wunkolo/Maple2Tools/releases/tag/v1.0

**Comment by babaisnyan** [comment]
Thanks!
